<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Webhook Inspector</title><style>body{font:15px system-ui;margin:0;background:#f7f7f8;color:#111}.wrap{max-width:1150px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:280px 1fr;gap:18px}.panel{background:#fff;border:1px solid #ddd;border-radius:10px;padding:18px;margin:12px 0}.row{display:flex;gap:8px;flex-wrap:wrap}button,input,textarea{padding:9px;border:1px solid #bbb;border-radius:7px}button{cursor:pointer}textarea{width:100%;min-height:150px;box-sizing:border-box}pre{background:#111;color:#eee;padding:14px;overflow:auto;border-radius:7px}.muted{color:#666}.tabs button{border:0;background:#eee}.tabs button.active{background:#111;color:#fff}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style></head><body><div class="wrap"><div class="top"><div><h1>Webhook Inspector</h1><p class="muted">Inspect, debug and replay HTTP webhooks.</p></div>@auth<form method="post" action="/logout">@csrf<button>Sign out</button></form>@else<a href="/login">Sign in</a>@endauth</div>@auth<div class="grid"><aside class="panel"><h2>Endpoints</h2><div class="row"><input id="name" placeholder="Endpoint name"><button onclick="createEndpoint()">Create</button></div><div id="list">Loading…</div></aside><main><div class="panel"><h2>Request Inspector</h2><div id="detail" class="muted">Select a captured request.</div></div><div class="panel"><h2>Replay</h2><label>Target URL</label><input id="target" style="width:100%;box-sizing:border-box" placeholder="https://example.com/webhook"><p>Headers JSON</p><textarea id="headers">{}</textarea><p>JSON payload</p><textarea id="payload">{}</textarea><button onclick="replay()">Execute replay</button><div id="replayResult"></div></div></main></div>@else<div class="panel"><p>Sign in to manage endpoints.</p></div>@endauth</div>@auth<script>
let current=null;
async function api(u,o={}){o.headers={...(o.headers||{}),Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':'{{csrf_token()}}'};return fetch(u,o)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function load(){let r=await api('/api/endpoints');if(!r.ok)return;let j=await r.json();document.querySelector('#list').innerHTML=j.map(e=>'<div class="panel"><b>'+esc(e.name)+'</b><p><code>'+esc(e.webhook_url)+'</code></p><div class="row"><button onclick="copyUrl(\''+encodeURIComponent(e.webhook_url)+'\')">Copy URL</button><button onclick="requests('+e.id+')">Requests</button><button onclick="regenerate('+e.id+')">Regenerate</button><button onclick="removeEndpoint('+e.id+')">Delete</button></div></div>').join('')||'<p class="muted">No endpoints.</p>'}
async function createEndpoint(){let n=document.querySelector('#name').value.trim();if(!n)return;let r=await api('/api/endpoints',{method:'POST',body:JSON.stringify({name:n})});if(!r.ok)return alert('Unable to create endpoint');document.querySelector('#name').value='';load()}
async function removeEndpoint(id){if(confirm('Delete endpoint?')){await api('/api/endpoints/'+id,{method:'DELETE'});load()}}
async function regenerate(id){if(confirm('Regenerate token? Existing webhook URL will stop working.')){await api('/api/endpoints/'+id+'/regenerate-token',{method:'POST'});load()}}
function copyUrl(v){navigator.clipboard.writeText(decodeURIComponent(v))}
async function requests(id){let r=await api('/api/endpoints/'+id+'/requests');let j=await r.json();document.querySelector('#list').querySelectorAll('button').forEach(()=>{});document.querySelector('#detail').innerHTML=(j.data||[]).map(x=>'<div class="panel"><b>'+esc(x.method)+'</b> · '+esc(x.received_at)+' · '+x.request_size+' bytes<button onclick="showRequest('+x.id+')">Inspect</button></div>').join('')||'<p class="muted">No captured requests.</p>'}
async function showRequest(id){current=id;let r=await api('/api/requests/'+id);let x=await r.json();document.querySelector('#detail').innerHTML='<div class="tabs"><button class="active">Overview</button></div><p><b>Method:</b> '+esc(x.method)+' <b>IP:</b> '+esc(x.ip_address)+' <b>User Agent:</b> '+esc(x.user_agent)+'</p><p><b>Received:</b> '+esc(x.received_at)+' <b>Size:</b> '+x.request_size+' bytes</p><h3>Headers</h3><pre>'+esc(JSON.stringify(x.headers,null,2))+'</pre><h3>Query</h3><pre>'+esc(JSON.stringify(x.query,null,2))+'</pre><h3>JSON</h3><pre>'+esc(JSON.stringify(x.json_body,null,2))+'</pre><h3>Raw Request</h3><pre>'+esc(x.raw_body)+'</pre><h3>Replay History</h3><pre>'+esc(JSON.stringify(x.replays,null,2))+'</pre>';document.querySelector('#payload').value=JSON.stringify(x.json_body||{},null,2)}
async function replay(){if(!current)return alert('Select a request first');let headers,payload;try{headers=JSON.parse(document.querySelector('#headers').value);payload=JSON.parse(document.querySelector('#payload').value)}catch(e){return alert('Headers and payload must be valid JSON')}let r=await api('/api/requests/'+current+'/replay',{method:'POST',body:JSON.stringify({target_url:document.querySelector('#target').value,headers,payload})});let j=await r.json();document.querySelector('#replayResult').innerHTML='<pre>'+esc(JSON.stringify(j,null,2))+'</pre>'}
load();
</script>@endauth</body></html>