<?php
namespace Tests\Feature;
use App\Models\User;use App\Models\WebhookEndpoint;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Http;use Tests\TestCase;
class WebhookInspectorTest extends TestCase {use RefreshDatabase;
public function test_endpoint_creation():void{$u=User::factory()->create();$this->actingAs($u)->postJson('/api/endpoints',['name'=>'Orders'])->assertCreated()->assertJsonPath('data.name','Orders');$this->assertDatabaseHas('webhook_endpoints',['name'=>'Orders','user_id'=>$u->id]);}
public function test_webhook_capture_json_headers_and_raw_body():void{$u=User::factory()->create();$e=WebhookEndpoint::create(['user_id'=>$u->id,'name'=>'Test','token'=>'abc123','enabled'=>true]);$this->postJson('/webhook/abc123',['order_id'=>42],['X-Test'=>'yes'])->assertAccepted();$this->assertDatabaseHas('webhook_requests',['webhook_endpoint_id'=>$e->id,'method'=>'POST']);}
public function test_authorization():void{$a=User::factory()->create();$b=User::factory()->create();$e=WebhookEndpoint::create(['user_id'=>$a->id,'name'=>'Private','token'=>'private','enabled'=>true]);$this->actingAs($b)->getJson('/api/endpoints/'.$e->id)->assertForbidden();}
public function test_deletion():void{$u=User::factory()->create();$e=WebhookEndpoint::create(['user_id'=>$u->id,'name'=>'Test','token'=>'delete','enabled'=>true]);$this->actingAs($u)->deleteJson('/api/endpoints/'.$e->id)->assertNoContent();$this->assertDatabaseMissing('webhook_endpoints',['id'=>$e->id]);}
public function test_replay_modification():void{$u=User::factory()->create();$e=WebhookEndpoint::create(['user_id'=>$u->id,'name'=>'Test','token'=>'replay','enabled'=>true]);$this->postJson('/webhook/replay',['original'=>true]);$r=$e->requests()->first();Http::fake(['https://example.com/*'=>Http::response(['ok'=>true],200)]);$this->actingAs($u)->postJson('/api/requests/'.$r->id.'/replay',['target_url'=>'https://example.com/hook','headers'=>['X-Custom'=>'changed'],'payload'=>['changed'=>true]])->assertCreated();Http::assertSent(fn($q)=>$q->header('X-Custom')==='changed'&&$q->data()['changed']===true);}
public function test_ssrf_private_ip_is_blocked():void{$u=User::factory()->create();$e=WebhookEndpoint::create(['user_id'=>$u->id,'name'=>'Test','token'=>'ssrf','enabled'=>true]);$this->postJson('/webhook/ssrf',['x'=>1]);$r=$e->requests()->first();$this->expectException(\RuntimeException::class);$this->actingAs($u)->postJson('/api/requests/'.$r->id.'/replay',['target_url'=>'http://127.0.0.1:8080']);}
}